databases:
  - name: fintrack-db
    databaseName: fintrack
    user: fintrack
    plan: free

services:
  - type: web
    name: fintrack
    env: python
    buildCommand: "./build.sh"
    startCommand: "poetry run python manage.py migrate && poetry run gunicorn django_finance.config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fintrack-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DJANGO_SETTINGS_MODULE
        value: django_finance.config.settings.base
      - key: DEBUG
        value: 'false'
      - key: NODE_VERSION
        value: "20.11.0"
